import { PUBLIC_SITE_URL } from '../siteUrl';

/** Demo providers when /api/marketplace is unavailable (e.g. local dev). Shape matches API + ProviderCard. */
export const SEED_MARKETPLACE_PROVIDERS = [
  {
    id: 'seed-0001-0000-0000-000000000001',
    category_id: 'warehouse_space',
    company_name: 'Crimson Logistics Indonesia (demo)',
    tagline: 'Bonded & FTZ warehouse — Batam & Jakarta',
    description: 'Contoh penyedia untuk pratinjau lokal. Daftar di TCG untuk listing asli.',
    logo_url: 'https://logo.clearbit.com/crimsonlogistics.co.id',
    website: PUBLIC_SITE_URL,
    country_codes: ['ID', 'SG'],
    certifications: ['ISO 9001', 'Bonded Warehouse'],
    plan_id: 'free',
    featured: true,
    verified: false,
    status: 'active',
  },
  {
    id: 'seed-0002-0000-0000-000000000002',
    category_id: 'logistics_services',
    company_name: 'TCG Express Network (demo)',
    tagline: 'Last-mile B2B & cross-border Asia',
    description: 'Data contoh — ganti dengan API produksi saat deployment.',
    logo_url: 'https://logo.clearbit.com/dhl.com',
    website: PUBLIC_SITE_URL,
    country_codes: ['SG', 'ID', 'MY'],
    certifications: ['ISO 9001', 'TAPA FSR'],
    plan_id: 'starter',
    featured: false,
    verified: false,
    status: 'active',
  },
  {
    id: 'seed-0003-0000-0000-000000000003',
    category_id: 'equipment_systems',
    company_name: 'Zebra Technologies Asia (demo)',
    tagline: 'RFID, barcode & mobile computing',
    description: 'Contoh vendor peralatan & sistem untuk pengembangan UI.',
    logo_url: 'https://logo.clearbit.com/zebra.com',
    website: PUBLIC_SITE_URL,
    country_codes: ['SG', 'ID', 'JP'],
    certifications: ['ISO 9001', 'CE Marking'],
    plan_id: 'free',
    featured: true,
    verified: false,
    status: 'active',
  },
  {
    id: 'seed-0004-0000-0000-000000000004',
    category_id: 'material_handling',
    company_name: 'Toyota Industries Asia (demo)',
    tagline: 'Forklifts & MHE — dealer Asia',
    description: 'Seed listing untuk localhost tanpa backend.',
    logo_url: 'https://logo.clearbit.com/toyota-industries.com',
    website: PUBLIC_SITE_URL,
    country_codes: ['JP', 'ID', 'SG'],
    certifications: ['ISO 9001', 'ISO 14001'],
    plan_id: 'pro',
    featured: false,
    verified: false,
    status: 'active',
  },
];
